# Generated by Django 4.2.13 on 2024-05-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reccommendationapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
