# Generated by Django 4.2.13 on 2024-05-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reccommendationapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="year_of_publication",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
